# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/src/Aida.Api/ClientApp"
    open-pull-requests-limit: 3
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/src/Aida.Api"
    open-pull-requests-limit: 3
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    # Look for a `Directory.Packages.props` in the `root` directory
    directory: "/"
    open-pull-requests-limit: 3
    # Check for updates once a week
    schedule:
      interval: "weekly"
