name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
      working-directory: src/Aida.Api/ClientApp
    - run: npm run build --if-present
      working-directory: src/Aida.Api/ClientApp
    - run: npm test
      working-directory: src/Aida.Api/ClientApp
      
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

      
    # deploy when you figure out how you want to host it.
