name: Deploy

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - ".github/workflows/pr-verify-backend.yml"
      - ".github/workflows/pr-verify-frontend.yml"
      - ".github/workflows/pr-verify-iac.yml"

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci
        working-directory: src/Aida.Api/ClientApp
      - run: npm run build --if-present
        working-directory: src/Aida.Api/ClientApp
      - run: npm run test:ci
        working-directory: src/Aida.Api/ClientApp

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore Aida.Api.UnitTests.csproj
        working-directory: tests/Aida.Api.UnitTests
      - name: Build
        run: dotnet build Aida.Api.UnitTests.csproj --no-restore
        working-directory: tests/Aida.Api.UnitTests
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: tests/Aida.Api.UnitTests

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: tests/Aida.Api.IntegrationTests
      - name: Build
        run: dotnet build --no-restore
        working-directory: tests/Aida.Api.IntegrationTests
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: tests/Aida.Api.IntegrationTests

    # deploy when you figure out how you want to host it.

