name: Frontend Verify

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**.tf"
      - "**.cs"
      - "**.csproj"
      - "**.sln"
      - "tests/**"
      - "src/Aida.Core/**"
      - ".github/workflows/pr-verify-backend.yml"
      - ".github/workflows/pr-verify-iac.yml"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Aida.Api/ClientApp

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:ci

