name: Backend Verify

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - ".github/workflows/pr-verify-iac.yml"
      - ".github/workflows/pr-verify-frontend.yml"

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore Aida.Api.UnitTests.csproj
        working-directory: tests/Aida.Api.UnitTests
      - name: Build
        run: dotnet build Aida.Api.UnitTests.csproj --no-restore
        working-directory: tests/Aida.Api.UnitTests
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: tests/Aida.Api.UnitTests

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: tests/Aida.Api.IntegrationTests
      - name: Build
        run: dotnet build --no-restore
        working-directory: tests/Aida.Api.IntegrationTests
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: tests/Aida.Api.IntegrationTests

