name: PR Verify IaC

on:
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    name: "Terraform - ${{ matrix.environment }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=aida-tfstate" \
            -backend-config="storage_account_name=aidatfstate" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=${{ matrix.environment }}.terraform.tfstate"

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ matrix.environment }}"

      - name: Terraform Validate
        run: terraform validate

