name: PR Verify IaC

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - ".github/workflows/pr-verify-backend.yml"
      - ".github/workflows/pr-verify-frontend.yml"

jobs:
  terraform:
    name: "Terraform - ${{ matrix.environment }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Terraform Environment Variables
        run: |
          # Parse AZURE_CREDENTIALS JSON
          echo '${{ secrets.AZURE_CREDENTIALS }}' > azure_credentials.json

          # Set ARM environment variables
          echo "ARM_CLIENT_ID=$(jq -r .clientId azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenantId azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azure_credentials.json)" >> $GITHUB_ENV

          # Clean up
          rm azure_credentials.json

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=aida-tfstate" \
            -backend-config="storage_account_name=aidatfstate" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=${{ matrix.environment }}.terraform.tfstate"

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ matrix.environment }}"

      - name: Terraform Validate
        run: terraform validate

